### ISSUE TITLE
C-M-. fails

### ISSUE THREAD

**Issue by fkautz** [sourcegraph/emacs-sourcegraph-mode#8] opened 2015-01-30 22:31 UTC
I get the following error message when trying to find golang definitions using C-M-.

Symbol's function definition is void: shr-render-region

**Comment by samertm** [comment] 2015-04-03 23:03
Thanks for submitting this bug report, the issue is that older version of Emacs don't have shr-render-region. Fixed by https://github.com/sourcegraph/emacs-sourcegraph-mode/commit/b86dd72d59edb5cd3ab9e6c2e544523d01eb7bf1, reopen this if you still see the issue.

**Closed by samertm** 2015-04-03 23:03 UTC
